title: Bedrock Wiki
email: sirlich.business@gmail.com
description: >-
  Legacy Wiki: Please visit wiki.bedrock.dev for updated site.

remote_theme: pmarsceill/just-the-docs
color_scheme: light

github_username:  SirLich

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/SirLich/bedrock-wiki" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

coderay_default_lang: JSON

kramdown:
  parse_block_html: true

markdown: kramdown
url: https://old-wiki.bedrock.dev/
aux_links:
  "Discord":
    - "/discord"
  "Bedrock.dev":
    - "https://bedrock.dev/"
  "Contribute":
    - "/contribute"
  "News":
   - "/news/"
  


# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

search_enabled: true


paginate: 10
paginate_path: "/news/page:num/"
excerpt_separator: <!--more-->

permalink: /:title
